/**
 * @file SerialThread.cpp
 * @brief MCU wire-owner. Plain MessageThread routing: pushCommand on RX,
 *        popStatus on TX. No mailbox, no registry.
 */

#include "SerialThread.h"

#include "System.h"   // System::servo / mass / leds
#include "packets.h"  // ids + wire structs

#include <cstring>

namespace {
/* Size-checked reinterpret of a frame payload as a wire struct.
 *
 * Returns false and leaves `out` untouched when the payload length does not
 * match the struct. It used to return a ZERO-FILLED struct in that case and the
 * caller dispatched it anyway, which is worse than dropping the frame: a
 * ServoRequest of the wrong length became {id 0, angle 0, go_to_zero 0} - a
 * valid command that MOVES servo 0 to 0 degrees. A length that does not match
 * means the wire contract drifted or the frame is noise; neither is a reason to
 * drive hardware. The RPi has always guarded this (Nexus::lengthOk); this is the
 * missing half on the MCU. */
template <class T, class Frame>
bool _frameas(const Frame& f, T& out) {
    if (f.length != sizeof(T)) return false;
    std::memcpy(&out, f.payload.data(), sizeof(T));
    return true;
}
} // namespace

SerialThread::SerialThread(const char* name, osPriority priority) : Thread(name, priority) {
    // Tick rate is NOT set here: every thread's is in System::init(), so the
    // whole schedule reads in one place.
}

void SerialThread::init() {
    _io.begin(); //init transport
}

/* Every live frame fits in ONE USB-FS bulk packet.
 *
 * Here and not in packets.h: that file is generated by gen_av_packets.sh and a
 * check written there is wiped on the next .msg change. This file is hand-owned
 * and names exactly the packets this link carries.
 *
 * Why it matters: a frame that fits one packet is delivered atomically, which is
 * what lets staleFrame() treat a mid-frame silence as evidence of loss rather
 * than of a slow sender. Exceed 64 and that reasoning quietly stops holding. */
static constexpr uint16_t OVER = SerialThread::Proto::FRAME_OVERHEAD;
static_assert(sizeof(ServoRequest) + OVER <= CdcTransport::USB_PACKET, "ServoRequest spans two USB packets");
static_assert(sizeof(MassRequest)  + OVER <= CdcTransport::USB_PACKET, "MassRequest spans two USB packets");
static_assert(sizeof(LEDRequest)   + OVER <= CdcTransport::USB_PACKET, "LEDRequest spans two USB packets");
static_assert(sizeof(PhRequest)    + OVER <= CdcTransport::USB_PACKET, "PhRequest spans two USB packets");
static_assert(sizeof(MassPacket)   + OVER <= CdcTransport::USB_PACKET, "MassPacket spans two USB packets");
static_assert(sizeof(PhPacket)     + OVER <= CdcTransport::USB_PACKET, "PhPacket spans two USB packets");
static_assert(sizeof(Heartbeat)    + OVER <= CdcTransport::USB_PACKET, "Heartbeat spans two USB packets");

void SerialThread::loop() {
    /* Service the link, then resync the parser if it came back. Runs first so a
     * recovered link sends this iteration's telemetry rather than waiting for
     * the next. Goes through the protocol, not the transport: after Phase 1.3
     * this thread's only contact with _io is begin(). */
    _proto.tick(xTaskGetTickCount());
    if (_proto.linkReset()) ++_linkResets;

    /* RX: serial -> worker command queues. The protocol owns the drain now -
     * this thread never touches _io on the data path, only begin() in init().
     * Thread -> Protocol -> Transport, one direction. */
    _proto.poll([this](const Frame& frame) { dispatch(frame); });

    /* TX: worker status queues -> serial */
    MassPacket mp;
    while (System::mass().popStatus(mp)) _proto.send(MassPacket_ID, &mp, sizeof mp);

    PhPacket pp;
    while (System::ph().popStatus(pp)) _proto.send(PhPacket_ID, &pp, sizeof pp);

    Heartbeat hb;
    while (System::heartbeat().popStatus(hb)) _proto.send(Heartbeat_ID, &hb, sizeof hb);
}

void SerialThread::dispatch(const Frame& f) {
    /* A frame whose payload is the wrong size for its id is REFUSED, not
     * dispatched zero-filled. Counted so a contract drift between the two sides
     * shows up as a number instead of as hardware doing something odd. */
    switch (f.id) {
        case ServoRequest_ID: {
            ServoRequest r;
            if (_frameas(f, r)) System::servo().pushCommand(r); else ++_badPayload;
            break;
        }
        case MassRequest_ID: {
            MassRequest r;
            if (_frameas(f, r)) System::mass().pushCommand(r); else ++_badPayload;
            break;
        }
        case LEDRequest_ID: {
            LEDRequest r;
            if (_frameas(f, r)) System::leds().pushCommand(r); else ++_badPayload;
            break;
        }
        case PhRequest_ID: {
            PhRequest r;
            if (_frameas(f, r)) System::ph().pushCommand(r); else ++_badPayload;
            break;
        }
        default: ++_unknownId; break;
    }
}
