# LEDMessage.msg
uint8 system
uint8 state

# Systems
#uint8       NAV         = 0
#uint8       HD          = 1
#uint8       DRILL       = 2
#uint8       AVIONICS    = 3

# Patterns
#uint8       OFF                = 0
#uint8       ON                 = 1
#uint8       BLINK              = 2
#uint8       FAULT              = 3
#uint8       EMERGENCY_MOTORS   = 4  --  This mode is not related to the subsystems
#uint8       EMERGENCY_SHUTDOWN = 5  --  This mode is not related to the subsystems
